name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Build Tools and Build
        shell: cmd
        run: |
          set NO_PAUSE=1
          call "#install_build_tools.bat"
          call "#build.bat"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build/libs/*.jar
