name: Build + Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build JAR and prepare dist folder
        shell: cmd
        run: |
          set NO_PAUSE=1
          call "#install_build_tools.bat"
          call "#build.bat"
          
          mkdir dist
          copy /Y index.html dist\index.html
          copy /Y README.md dist\README.md
          copy /Y knowledge_book.png dist\knowledge_book.png
          :: copy /Y meteor-client-1.21.11-82.jar dist\meteor-client-1.21.11-82.jar
          :: copy /Y build\libs\meteor-RyanWare-0.1-addon.jar dist\RyanWare-addon.jar
          :: copy /Y build\libs\meteor-RyanWare-0.1-standalone.jar dist\RyanWare-standalone.jar

      - name: Upload Pages Site
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy Pages
        uses: actions/deploy-pages@v4